[package]
name = "ShelbyVault"
version = "1.0.0"

[addresses]
shelby_vault = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

